-- System categories. GENERATED from packages/core/src/defaultCategories.ts by `npm run gen:seed`. Do not edit by hand.
insert into public.categories (id, user_id, parent_id, name, kind) values
  ('cat.food', null, null, 'Food', 'expense'),
  ('cat.food.groceries', null, 'cat.food', 'Groceries', 'expense'),
  ('cat.food.dining', null, 'cat.food', 'Dining', 'expense'),
  ('cat.food.coffee', null, 'cat.food', 'Coffee', 'expense'),
  ('cat.food.delivery', null, 'cat.food', 'Delivery', 'expense'),
  ('cat.transport', null, null, 'Transport', 'expense'),
  ('cat.transport.fuel', null, 'cat.transport', 'Fuel', 'expense'),
  ('cat.transport.ride_share', null, 'cat.transport', 'Ride share', 'expense'),
  ('cat.transport.public_transport', null, 'cat.transport', 'Public transport', 'expense'),
  ('cat.transport.parking', null, 'cat.transport', 'Parking', 'expense'),
  ('cat.bills', null, null, 'Bills', 'expense'),
  ('cat.bills.electricity', null, 'cat.bills', 'Electricity', 'expense'),
  ('cat.bills.internet', null, 'cat.bills', 'Internet', 'expense'),
  ('cat.bills.mobile', null, 'cat.bills', 'Mobile', 'expense'),
  ('cat.bills.water', null, 'cat.bills', 'Water', 'expense'),
  ('cat.bills.rent', null, 'cat.bills', 'Rent', 'expense'),
  ('cat.shopping', null, null, 'Shopping', 'expense'),
  ('cat.shopping.clothing', null, 'cat.shopping', 'Clothing', 'expense'),
  ('cat.shopping.electronics', null, 'cat.shopping', 'Electronics', 'expense'),
  ('cat.shopping.household', null, 'cat.shopping', 'Household', 'expense'),
  ('cat.shopping.personal_care', null, 'cat.shopping', 'Personal care', 'expense'),
  ('cat.health', null, null, 'Health', 'expense'),
  ('cat.health.medicine', null, 'cat.health', 'Medicine', 'expense'),
  ('cat.health.doctor', null, 'cat.health', 'Doctor', 'expense'),
  ('cat.health.fitness', null, 'cat.health', 'Fitness', 'expense'),
  ('cat.entertainment', null, null, 'Entertainment', 'expense'),
  ('cat.entertainment.movies', null, 'cat.entertainment', 'Movies', 'expense'),
  ('cat.entertainment.games', null, 'cat.entertainment', 'Games', 'expense'),
  ('cat.entertainment.events', null, 'cat.entertainment', 'Events', 'expense'),
  ('cat.entertainment.streaming', null, 'cat.entertainment', 'Streaming', 'expense'),
  ('cat.education', null, null, 'Education', 'expense'),
  ('cat.education.courses', null, 'cat.education', 'Courses', 'expense'),
  ('cat.education.books', null, 'cat.education', 'Books', 'expense'),
  ('cat.education.tuition', null, 'cat.education', 'Tuition', 'expense'),
  ('cat.family', null, null, 'Family', 'expense'),
  ('cat.family.children', null, 'cat.family', 'Children', 'expense'),
  ('cat.family.parents', null, 'cat.family', 'Parents', 'expense'),
  ('cat.family.gifts', null, 'cat.family', 'Gifts', 'expense'),
  ('cat.family.household_support', null, 'cat.family', 'Household support', 'expense'),
  ('cat.finance', null, null, 'Finance', 'expense'),
  ('cat.finance.fees', null, 'cat.finance', 'Fees', 'expense'),
  ('cat.finance.interest', null, 'cat.finance', 'Interest', 'expense'),
  ('cat.finance.loan_payment', null, 'cat.finance', 'Loan payment', 'expense'),
  ('cat.travel', null, null, 'Travel', 'expense'),
  ('cat.travel.flights', null, 'cat.travel', 'Flights', 'expense'),
  ('cat.travel.hotel', null, 'cat.travel', 'Hotel', 'expense'),
  ('cat.travel.local_travel', null, 'cat.travel', 'Local travel', 'expense'),
  ('cat.other', null, null, 'Other', 'expense'),
  ('cat.other.miscellaneous', null, 'cat.other', 'Miscellaneous', 'expense'),
  ('cat.income.salary', null, null, 'Salary', 'income'),
  ('cat.income.business', null, null, 'Business', 'income'),
  ('cat.income.freelance', null, null, 'Freelance', 'income'),
  ('cat.income.gift', null, null, 'Gift', 'income'),
  ('cat.income.investment', null, null, 'Investment', 'income'),
  ('cat.income.other_income', null, null, 'Other income', 'income')
on conflict (id) do nothing;
